# Generated by Django 5.0.6 on 2025-08-11 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sync State',
                'verbose_name_plural': 'Sync States',
                'db_table': 'sync_state',
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('check_time', models.DateTimeField()),
                ('log_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='employees.employee')),
            ],
            options={
                'db_table': 'attendance_logs',
                'ordering': ['-check_time'],
                'indexes': [models.Index(fields=['employee', 'check_time'], name='idx_att_employee_time'), models.Index(fields=['check_time'], name='idx_att_time')],
            },
        ),
    ]
