# Generated by Django 5.0.6 on 2025-08-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncstate',
            name='last_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncstate',
            name='last_error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
