name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: atlas
          POSTGRES_USER: atlas
          POSTGRES_PASSWORD: atlas
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U atlas -d atlas" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Django check
        env:
          DATABASE_URL: postgresql+psycopg://atlas:atlas@localhost:5432/atlas
        run: |
          python manage.py check
      - name: Lint
        run: |
          flake8 .
      - name: Tests
        env:
          DATABASE_URL: postgresql+psycopg://atlas:atlas@localhost:5432/atlas
          DJANGO_DEBUG: true
          DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
        run: |
          python manage.py migrate
          pytest -q